# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedditLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.TextField()),
                ('link', models.TextField()),
                ('pub_date', models.DateTimeField()),
                ('data_fullname', models.CharField(max_length=20)),
            ],
        ),
    ]
